name: Build OCI Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: 
      image: catthehacker/ubuntu:act-22.04
    env: 
      DOCKER_CONFIG: '~/.docker/'
    steps:
    - name: buildx setup
      uses: docker/setup-buildx-action@v3
      with:
        use: true
        platforms: linux/amd64,linux/arm64 
    - name: oci metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
         ghcr.io/${{ github.repository }}
        tags: |
          type=sha,event=branch
        labels: |
          org.opencontainers.image.description=A buildkit runner
    - name: oci build
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        platforms: linux/arm64,linux/amd64
        build-args: BUILDKIT_TAG=v0.15.1
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
