name: Build OCI Image

on:
  push:
    tags:
      - 'v*'

# Permissions to be given to the GITHUB_TOKEN for this workflow
permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container: 
      image: catthehacker/ubuntu:act-22.04
    env: 
      DOCKER_CONFIG: '~/.docker/'
    steps:
    - name: buildx setup
      uses: docker/setup-buildx-action@v3
      with:
        use: true
        platforms: linux/amd64,linux/arm64 
    - name: oci metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
        labels: |
          org.opencontainers.image.description=A buildkit runner
    - name: oci login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        # Use the built-in GitHub action token for authentication with ghcr
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: oci build
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        platforms: linux/arm64,linux/amd64
        build-args: BUILDKIT_TAG=v0.15.1
        # Only push package if triggered by tag and prevent anyone from creating tags using tag-protection for this repository
        # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules
        push: ${{ github.ref_type == 'tag' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
